//      *********    DO NOT MODIFY THIS FILE     *********
//      This file is regenerated by a design tool. Making
//      changes to this file can cause errors.
namespace Expression.Blend.SampleData.SampleDataSource
{
	using System; 

// To significantly reduce the sample data footprint in your production application, you can set
// the DISABLE_SAMPLE_DATA conditional compilation constant and disable sample data at runtime.
#if DISABLE_SAMPLE_DATA
	internal class SampleDataSource { }
#else

	public class SampleDataSource : System.ComponentModel.INotifyPropertyChanged
	{
		public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;

		protected virtual void OnPropertyChanged(string propertyName)
		{
			if (this.PropertyChanged != null)
			{
				this.PropertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
			}
		}

		public SampleDataSource()
		{
			try
			{
				System.Uri resourceUri = new System.Uri("/SilverlightApplication2;component/SampleData/SampleDataSource/SampleDataSource.xaml", System.UriKind.Relative);
				if (System.Windows.Application.GetResourceStream(resourceUri) != null)
				{
					System.Windows.Application.LoadComponent(this, resourceUri);
				}
			}
			catch (System.Exception)
			{
			}
		}

		private Products _Products = new Products();

		public Products Products
		{
			get
			{
				return this._Products;
			}
		}
	}

	public class ProductsItem : System.ComponentModel.INotifyPropertyChanged
	{
		public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;

		protected virtual void OnPropertyChanged(string propertyName)
		{
			if (this.PropertyChanged != null)
			{
				this.PropertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
			}
		}

		private string _ProductName = string.Empty;

		public string ProductName
		{
			get
			{
				return this._ProductName;
			}

			set
			{
				if (this._ProductName != value)
				{
					this._ProductName = value;
					this.OnPropertyChanged("ProductName");
				}
			}
		}

		private System.Windows.Media.ImageSource _ProductImageUrl = null;

		public System.Windows.Media.ImageSource ProductImageUrl
		{
			get
			{
				return this._ProductImageUrl;
			}

			set
			{
				if (this._ProductImageUrl != value)
				{
					this._ProductImageUrl = value;
					this.OnPropertyChanged("ProductImageUrl");
				}
			}
		}
	}

	public class Products : System.Collections.ObjectModel.ObservableCollection<ProductsItem>
	{ 
	}
#endif
}
